// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLqlOAQfBWySq7Q9p-yWQzY2vctzGENfo',
    appId: '1:451992206309:android:2886ca93c4c607d98c8d0c',
    messagingSenderId: '451992206309',
    projectId: 'push-notifications-f4b46',
    storageBucket: 'push-notifications-f4b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARikMOtek0WSVDf_w1yl0QCqK1oIEz4C4',
    appId: '1:451992206309:ios:794820b0c802770b8c8d0c',
    messagingSenderId: '451992206309',
    projectId: 'push-notifications-f4b46',
    storageBucket: 'push-notifications-f4b46.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi4Qfi_gZKGXPxmlPhF-pf3oAtIP0cpf0',
    appId: '1:451992206309:web:7130591ace8019ae8c8d0c',
    messagingSenderId: '451992206309',
    projectId: 'push-notifications-f4b46',
    authDomain: 'push-notifications-f4b46.firebaseapp.com',
    storageBucket: 'push-notifications-f4b46.appspot.com',
    measurementId: 'G-TY5CGJFJ1X',
  );
}
